### ISSUE TITLE
Is there are reason we can't convert wikilinks to markdown links?

### ISSUE THREAD

**Issue by ltroj** [Benature/obsidian-text-format#40]
I was wondering why there is a command ``Convert URL links to WikiLinks in selection`` but not the other way round?

It would be great to be able to convert an (Obsidian) wikilink to plain markdown (with an option to set an absolute or a relative path).

**Comment by Benature** [comment]
v2.6.0 has supportted this feature, please have a try! 

Free feel to reopen this issue if something is wrong.

**Comment by ltroj** [comment]
Thank you, works like a charm!

**Comment by machado-t** [comment]
I'm encountering issues with the "Convert WikiLinks to plain Markdown links" feature affecting attachments and the handling of spaces in WikiLinks.

### Description:

1. **Attachments receive ".md" extension:** When converting WikiLinks for attachments, a ".md" extension is incorrectly added (e.g., `![[image.png]]` becomes `![image.png](image.png.md)` instead of `![image.png](image.png))`.

2. **Inconsistent handling of spaces in WikiLinks:** WikiLinks to notes handle spaces correctly by replacing them with %20 (e.g., `[[Example Note]]` converts to `[Example Note](Example%20Note.md))`, but attachments with spaces break during conversion because the spaces remain unescaped (e.g., `![[my image.png]]` converts to `![my image](my image.png)` instead of `![my image](my%20image.png))` or `![my image](<my image.png>)` .

### Steps to reproduce:

Use the "Convert WikiLinks to plain Markdown links" feature on:
- A WikiLink to an attachment (e.g., `![[image.png]])`.
- A WikiLink to an attachment or note containing spaces (e.g., `![[my image.png]]` or `[[Example Note]]`).

**Comment by machado-t** [comment]
Update: Found https://github.com/mii-key/obsidian-links which works great for my use case.
