### ISSUE TITLE
Command ribbon icon on iOS

### ISSUE THREAD

**Issue by srustamo** [Benature/obsidian-text-format#81]
This shows as a question mark for all commands 

![image](https://github.com/Benature/obsidian-text-format/assets/749813/026282ea-9b86-4b67-a217-2a3776784e49)

**Comment by Benature** [comment]
Where is this screenshot from?

**Comment by srustamo** [comment]
iPad Pro, iPadOS 17.3.1
![Screenshot 2024-03-12 at 10 44 07 jpeg](https://github.com/Benature/obsidian-text-format/assets/749813/a8a3f075-0193-48a9-8f9a-4c40bb589b56)

**Comment by Benature** [comment]
> This shows as a question mark for all commands
> 
> ![image](https://private-user-images.githubusercontent.com/749813/311672976-026282ea-9b86-4b67-a217-2a3776784e49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjMzMjIsIm5iZiI6MTcxMDIyMzAyMiwicGF0aCI6Ii83NDk4MTMvMzExNjcyOTc2LTAyNjI4MmVhLTliODYtNGI2Ny1hMjE3LTJhMzc3Njc4NGU0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwNTU3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjA2ODRjZmYwYTQyODJhNzhhYzE3YzNjNDE5N2M3YzAwY2Q5OWZlNWJjYTQ3OTg1MGE1OGZiY2I5YTIwNmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ro2a6UcqmR3m6qKaWMFVnuErKnO8MaVH7Ox7Pi9zmg)

Where is the view in this screenshot? Like the settings of a plugin?

**Comment by srustamo** [comment]
Obsidian Options menu.
![Screenshot 2024-03-12 at 11 00 09 jpeg](https://github.com/Benature/obsidian-text-format/assets/749813/7fed5c5a-f974-44b4-8b17-ea5e95af7a26)

**Comment by Benature** [comment]
According to [document](https://docs.obsidian.md/Plugins/User+interface/Icons), [lucide.dev](https://lucide.dev/) shows all available icons and their corresponding names.

The priority of this issue is not very high (i.e., it may not be done soon), but any participation is welcomed! Anyone who is interested can make a PR, or simply comment on this issue that which command should be with which icon. The mentioned command will be updated its icon along with other features are updated.
